### ISSUE TITLE
Updated windows cookbook breaks default recipe

### ISSUE THREAD

**Issue by austinlparker** [TAMUArch/cookbook.windows_ad#106]
Yesterday, the Windows cookbook was updated to version 3.0.0. When using this new cookbook, the default recipe no longer functions properly.

```
==> boxcar-dc: Recipe: windows_ad::default
==> boxcar-dc:   * windows_feature[Microsoft-Windows-GroupPolicy-ServerAdmintools-Update] action install
==> boxcar-dc:     * windows_feature_dism[Microsoft-Windows-GroupPolicy-ServerAdmintools-Update] action install
==> boxcar-dc:
==> boxcar-dc:       ================================================================================
==> boxcar-dc:       Error executing action `install` on resource 'windows_feature_dism[Microsoft-Windows-GroupPolicy-ServerAdmintools-Update]'
==> boxcar-dc:       ================================================================================
==> boxcar-dc:       NoMethodError
==> boxcar-dc:       -------------
==> boxcar-dc:       undefined method `feature' for Custom resource windows_feature_dism from cookbook windows
==> boxcar-dc:       Cookbook Trace:
==> boxcar-dc:       ---------------
==> boxcar-dc:       C:/chef/cache/cookbooks/windows/resources/feature_dism.rb:77:in `block in class_from_file'
==> boxcar-dc:       Resource Declaration:
==> boxcar-dc:       ---------------------
==> boxcar-dc:       # In C:/chef/cache/cookbooks/windows/resources/feature.rb
==> boxcar-dc:
==> boxcar-dc:        44:       windows_feature_dism new_resource.name do
==> boxcar-dc:        45:         action desired_action
==> boxcar-dc:        46:         feature_name new_resource.feature_name
==> boxcar-dc:        47:         source new_resource.source if new_resource.source
==> boxcar-dc:        48:         all new_resource.all
==> boxcar-dc:        49:       end
==> boxcar-dc:        50:     when :windows_feature_servermanagercmd
==> boxcar-dc:
==> boxcar-dc:       Compiled Resource:
==> boxcar-dc:       ------------------
==> boxcar-dc:       # Declared in C:/chef/cache/cookbooks/windows/resources/feature.rb:44:in `run_default_provider'
==> boxcar-dc:
==> boxcar-dc:       windows_feature_dism("Microsoft-Windows-GroupPolicy-ServerAdmintools-Update") do
==> boxcar-dc:         action [:install]
==> boxcar-dc:         retries 0
==> boxcar-dc:         retry_delay 2
==> boxcar-dc:         default_guard_interpreter :default
==> boxcar-dc:         declared_type :windows_feature_dism
==> boxcar-dc:         cookbook_name "windows_ad"
==> boxcar-dc:         feature_name "Microsoft-Windows-GroupPolicy-ServerAdmintools-Update"
==> boxcar-dc:         all false
==> boxcar-dc:       end
==> boxcar-dc:
==> boxcar-dc:       Platform:
==> boxcar-dc:       ---------
==> boxcar-dc:       x64-mingw32
==> boxcar-dc: [2017-03-16T11:01:26-07:00] INFO: Running queued delayed notifications before re-raising exception
==> boxcar-dc:
==> boxcar-dc:     ================================================================================
==> boxcar-dc:     Error executing action `install` on resource 'windows_feature[Microsoft-Windows-GroupPolicy-ServerAdmintools-Update]'
==> boxcar-dc:     ================================================================================
==> boxcar-dc:     NoMethodError
==> boxcar-dc:     -------------
==> boxcar-dc:     windows_feature_dism[Microsoft-Windows-GroupPolicy-ServerAdmintools-Update] (C:/chef/cache/cookbooks/windows/resources/feature.rb line 44) had an error: NoMethodError: undefined method `feature' for Custom resource windows_feature_dism from cookbook windows
==> boxcar-dc:     Cookbook Trace:
==> boxcar-dc:     ---------------
==> boxcar-dc:     C:/chef/cache/cookbooks/windows/resources/feature_dism.rb:77:in `block in class_from_file'
==> boxcar-dc:     Resource Declaration:
==> boxcar-dc:     ---------------------
==> boxcar-dc:     # In C:/chef/cache/cookbooks/windows_ad/recipes/default.rb
==> boxcar-dc:
==> boxcar-dc:      39:     windows_feature feature do
==> boxcar-dc:      40:       action :install
==> boxcar-dc:      41:     end
==> boxcar-dc:      42:   end
==> boxcar-dc:
==> boxcar-dc:     Compiled Resource:
==> boxcar-dc:     ------------------
==> boxcar-dc:     # Declared in C:/chef/cache/cookbooks/windows_ad/recipes/default.rb:39:in `block in from_file'
==> boxcar-dc:
==> boxcar-dc:     windows_feature("Microsoft-Windows-GroupPolicy-ServerAdmintools-Update") do
==> boxcar-dc:       action [:install]
==> boxcar-dc:       retries 0
==> boxcar-dc:       retry_delay 2
==> boxcar-dc:       default_guard_interpreter :default
==> boxcar-dc:       declared_type :windows_feature
==> boxcar-dc:       cookbook_name "windows_ad"
==> boxcar-dc:       recipe_name "default"
==> boxcar-dc:       feature_name "Microsoft-Windows-GroupPolicy-ServerAdmintools-Update"
==> boxcar-dc:     end
==> boxcar-dc:
==> boxcar-dc:     Platform:
==> boxcar-dc:     ---------
==> boxcar-dc:     x64-mingw32
==> boxcar-dc: [2017-03-16T11:01:26-07:00] INFO: Running queued delayed notifications before re-raising exception
==> boxcar-dc:
==> boxcar-dc: Running handlers:
==> boxcar-dc: [2017-03-16T11:01:26-07:00] ERROR: Running exception handlers
==> boxcar-dc: Running handlers complete
==> boxcar-dc: [2017-03-16T11:01:26-07:00] ERROR: Exception handlers complete
==> boxcar-dc: Chef Client failed. 44 resources updated in 05 minutes 28 seconds
==> boxcar-dc: [2017-03-16T11:01:26-07:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
==> boxcar-dc: [2017-03-16T11:01:26-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> boxcar-dc: [2017-03-16T11:01:26-07:00] FATAL: NoMethodError: windows_feature[Microsoft-Windows-GroupPolicy-ServerAdmintools-Update] (windows_ad::default line 39) had an error: NoMethodError: windows_feature_dism[Microsoft-Windows-GroupPolicy-ServerAdmintools-Update] (C:/chef/cache/cookbooks/windows/resources/feature.rb line 44) had an error: NoMethodError: undefined method `feature' for Custom resource windows_feature_dism from cookbook windows
```

I was able to fix this by pinning the required windows cookbook version to 2.1.1

**Comment by derekgroh** [comment]
Fixed
