### ISSUE TITLE
for entering chef-client command getting error like dis below

### ISSUE THREAD

**Issue by devopsjith** [TAMUArch/cookbook.windows_ad#120]

**Comment by devopsjith** [comment]
[root@ip-172-31-21-79 ~]# chef-client
Starting Chef Client, version 14.8.12
resolving cookbooks for run list: ["nginx"]
Synchronizing Cookbooks:
  - nginx (0.1.7)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 7 resources
Recipe: nginx::removeapache
  * service[httpd] action stop (up to date)
  * yum_package[httpd] action remove

    ================================================================================
    Error executing action `remove` on resource 'yum_package[httpd]'
    ================================================================================

    RuntimeError
    ------------
    yum-helper.py had stderr/stdout output:

    Traceback (most recent call last):
      File "/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/provider/package/yum/yum_helper.py", line 203, in <module>
        query(command)
      File "/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/provider/package/yum/yum_helper.py", line 88, in query
        enabled_repos = base.repos.listEnabled()
      File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1070, in <lambda>
        repos = property(fget=lambda self: self._getRepos(),
      File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 686, in _getRepos
        self.conf # touch the config class first
      File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1078, in <lambda>
        conf = property(fget=lambda self: self._getConfig(),
      File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 420, in _getConfig
        self.plugins.run('init')
      File "/usr/lib/python2.7/site-packages/yum/plugins.py", line 188, in run
        func(conduitcls(self, self.base, conf, **kwargs))
      File "/usr/lib/yum-plugins/amazon-id.py", line 51, in init_hook
        repos = conduit.getRepos()
      File "/usr/lib/python2.7/site-packages/yum/plugins.py", line 601, in getRepos
        return self._base.repos
      File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1070, in <lambda>
        repos = property(fget=lambda self: self._getRepos(),
      File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 694, in _getRepos
        self.getReposFromConfig()
      File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 567, in getReposFromConfig
        self.getReposFromConfigFile(repofn, repo_age=thisrepo_age)
      File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 465, in getReposFromConfigFile
        raise Errors.ConfigError(exception2msg(e))
    yum.Errors.ConfigError: File contains parsing errors: file:///etc/yum.repos.d/nginx.repo
        [line  2]:     name=nginx repo

        [line  3]:     baseurl=http://nginx.org/packages/mainline/centos/7/x86_64/

        [line  4]:     gpgcheck=0

        [line  5]:     enabled=1

    Loaded plugins: amazon-id, rhui-lb

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/nginx/recipes/removeapache.rb

     13: package apache_package_name do
     14:     action :remove
     15: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/nginx/recipes/removeapache.rb:13:in `from_file'

    yum_package("httpd") do
      package_name "httpd"
      action [:remove]
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "nginx"
      recipe_name "removeapache"
    end

    System Info:
    ------------
    chef_version=14.8.12
    platform=redhat
    platform_version=7.5
    ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
    program_name=/bin/chef-client
    executable=/opt/chef/bin/chef-client


Running handlers:
[2018-12-29T11:54:48+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-12-29T11:54:48+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 08 seconds
[2018-12-29T11:54:49+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-12-29T11:54:49+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-12-29T11:54:49+00:00] FATAL: RuntimeError: yum_package[httpd] (nginx::removeapache line 13) had an error: RuntimeError: yum-helper.py had stderr/stdout output:

Traceback (most recent call last):
  File "/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/provider/package/yum/yum_helper.py", line 203, in <module>
    query(command)
  File "/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/provider/package/yum/yum_helper.py", line 88, in query
    enabled_repos = base.repos.listEnabled()
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1070, in <lambda>
    repos = property(fget=lambda self: self._getRepos(),
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 686, in _getRepos
    self.conf # touch the config class first
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1078, in <lambda>
    conf = property(fget=lambda self: self._getConfig(),
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 420, in _getConfig
    self.plugins.run('init')
  File "/usr/lib/python2.7/site-packages/yum/plugins.py", line 188, in run
    func(conduitcls(self, self.base, conf, **kwargs))
  File "/usr/lib/yum-plugins/amazon-id.py", line 51, in init_hook
    repos = conduit.getRepos()
  File "/usr/lib/python2.7/site-packages/yum/plugins.py", line 601, in getRepos
    return self._base.repos
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1070, in <lambda>
    repos = property(fget=lambda self: self._getRepos(),
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 694, in _getRepos
    self.getReposFromConfig()
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 567, in getReposFromConfig
    self.getReposFromConfigFile(repofn, repo_age=thisrepo_age)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 465, in getReposFromConfigFile
    raise Errors.ConfigError(exception2msg(e))
yum.Errors.ConfigError: File contains parsing errors: file:///etc/yum.repos.d/nginx.repo
        [line  2]:     name=nginx repo

        [line  3]:     baseurl=http://nginx.org/packages/mainline/centos/7/x86_64/

        [line  4]:     gpgcheck=0

        [line  5]:     enabled=1

Loaded plugins: amazon-id, rhui-lb

[root@ip-172-31-21-79 ~]#

**Comment by derekgroh** [comment]
Why are we trying to remove a Linux package from a windows system?

**Comment by derekgroh** [comment]
@devopsjith as this doesn’t directly deal with the windows_ad cookbook, this issue will be closed.
